# Generated by Django 3.0.4 on 2020-05-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=False)),
                ('adjunto', models.FileField(upload_to='')),
            ],
        ),
    ]
