# Generated by Django 3.0.4 on 2020-05-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tareas',
            new_name='Tarea',
        ),
    ]
