# Generated by Django 3.0.4 on 2020-05-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20200511_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
