# Generated by Django 3.0.4 on 2020-05-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20200512_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
